name: Main

on: status

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo $GITHUB_CONTEXT
    - name: Output payload contents
      run: cat $GITHUB_EVENT_PATH
